Fix error handler
warning, error and debug methods were calling itself with a wrong param structure instead of the log method.

TypeError: error() takes 2 positional arguments but 3 were given